# Generated by Django 4.1.5 on 2023-03-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='linked_in',
            new_name='LinkedIn',
        ),
    ]
