# Generated by Django 4.1.5 on 2023-03-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_member_position_alter_member_vertical_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.ImageField(default='Headshots/None/temp.jpeg', upload_to='Headshots/'),
        ),
    ]
