# Generated by Django 4.1.5 on 2023-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_member_headshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='headshot',
            field=models.ImageField(default='Headshots/None/headshot_default.jpeg', upload_to='Headshots/'),
        ),
    ]
