# Generated by Django 4.1.5 on 2023-03-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_member_order_alter_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='display',
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Co-Chair', 'Co-Chair'), ('PM/Director', 'PM/Director'), ('Senior Investment Analyst', 'Senior Investment Analyst'), ('Junior Investment Analyst', 'Junior Investment Analyst'), ('Team Photo', 'Team Photo'), ('No Display', 'No Display')], default='No Display', max_length=30),
        ),
    ]
