# Generated by Django 4.1.5 on 2023-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_member_do_not_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('No Display', 'No Display'), ('Co-Chair', 'Co-Chair'), ('PM/Director', 'PM/Director'), ('Senior Investment Analyst', 'Senior Investment Analyst'), ('Junior Investment Analyst', 'Junior Investment Analyst'), ('Team Photo', 'Team Photo')], default='No Display', max_length=30),
        ),
    ]
