# Generated by Django 4.1.5 on 2023-03-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_member_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='vertical',
            field=models.CharField(blank=True, choices=[('Industrials', 'Industrials'), ('Technology, Media & Telecom', 'Technology, Media & Telecom'), ('Consumers & Healthcare', 'Consumers & Healthcare'), ('Energy & Commodities', 'Energy & Commodities'), ('Finance, Insurance & Real Estate', 'Finance, Insurance & Real Estate'), ('Market & Trends', 'Market & Trends'), ('Analytics', 'Analytics'), ('Investments Team', 'Investments Team')], default='', max_length=100, null=True),
        ),
    ]
