# Generated by Django 4.0.8 on 2023-04-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_member_vertical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='vertical',
            field=models.CharField(blank=True, choices=[('Investments Team', 'Investments Team'), ('Industrials', 'Industrials'), ('Technology, Media & Telecom', 'Technology, Media & Telecom'), ('Consumers & Healthcare', 'Consumers & Healthcare'), ('Energy & Commodities', 'Energy & Commodities'), ('Finance, Insurance & Real Estate', 'Finance, Insurance & Real Estate'), ('Market & Trends', 'Market & Trends'), ('Analytics', 'Analytics')], default='', max_length=100, null=True),
        ),
    ]
