# Generated by Django 4.1.5 on 2023-02-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
