# Generated by Django 4.1.5 on 2023-03-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_description_remove_report_pdf_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='pdf',
            field=models.FileField(default='Pdfs/None/pdf_default.pdf', upload_to='Pdfs/'),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='image',
            field=models.ImageField(default='Images/None/image_default.png', upload_to='Images/'),
        ),
    ]
