# Generated by Django 4.1.5 on 2023-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_pdf_alter_reportimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
