# Generated by Django 4.1.5 on 2023-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_order_reportimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
