# Generated by Django 4.1.5 on 2023-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_alter_report_display_alter_reportimage_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='display',
        ),
        migrations.RemoveField(
            model_name='reportimage',
            name='display',
        ),
        migrations.AddField(
            model_name='report',
            name='do_not_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='do_not_display',
            field=models.BooleanField(default=False),
        ),
    ]
