# Generated by Django 4.1.5 on 2023-01-30 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitches',
            name='user',
        ),
    ]
