# Generated by Django 4.1.5 on 2023-02-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0002_remove_pitches_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitches',
            name='pdf_link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
