# Generated by Django 4.1.5 on 2023-02-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0004_pitchphotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pitches',
            new_name='Pitch',
        ),
        migrations.RenameModel(
            old_name='PitchPhotos',
            new_name='PitchImage',
        ),
    ]
