# Generated by Django 4.1.5 on 2023-02-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0005_rename_pitches_pitch_rename_pitchphotos_pitchimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchimage',
            name='image',
            field=models.ImageField(default='Images/None/No0img.jpg', upload_to='Images/'),
        ),
    ]
