# Generated by Django 4.1.5 on 2023-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0007_pitch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchimage',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
