# Generated by Django 4.1.5 on 2023-02-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0008_pitch_display_pitchimage_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='pdf_link',
        ),
        migrations.AddField(
            model_name='pitch',
            name='pdf',
            field=models.ImageField(default='Pdfs/None/No0pdf.pdf', upload_to='Pdfs/'),
        ),
    ]
