# Generated by Django 4.1.5 on 2023-02-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0009_remove_pitch_pdf_link_pitch_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='user',
        ),
    ]
