# Generated by Django 4.1.5 on 2023-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0010_remove_pitch_description_remove_pitch_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitch',
            name='pdf',
            field=models.FileField(default='Pdfs/None/No0pdf.pdf', upload_to='Pdfs/'),
        ),
    ]
