# Generated by Django 4.1.5 on 2023-03-08 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0013_pitch_order_pitchimage_order_alter_pitch_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchimage',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
