# Generated by Django 4.1.5 on 2023-03-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0014_alter_pitchimage_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='display',
        ),
        migrations.RemoveField(
            model_name='pitchimage',
            name='display',
        ),
        migrations.AddField(
            model_name='pitch',
            name='do_not_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pitchimage',
            name='do_not_display',
            field=models.BooleanField(default=False),
        ),
    ]
