# Generated by Django 4.1.5 on 2023-03-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitches', '0015_remove_pitch_display_remove_pitchimage_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='cover',
            field=models.ImageField(default='Images/None/image_default.png', upload_to='Images/'),
        ),
    ]
